default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails_ci
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
